<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CourseRequisites extends Model
{
    protected $fillable = [
        'course_id',
        'requisite_type',
        'requisite_value',
    ];

    public function course()
    {
        return $this->belongsTo('App\Course');
    }

    public function getCourseNameAttribute($course = null)
    {
        if(strcasecmp($this->requisite_type, 'certification')===0) {
            return Course::FindOrFail($this->requisite_value)->course;
        }
    }



    public function __toString()
    {
        $this->course_name;
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

}
